# Generated by Django 5.2.5

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('rannaghoreprotidinapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create Products model
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('p_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.CharField(max_length=100)),
                ('brief_description', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='no_image.png', null=True, upload_to='products_img')),
                ('sku', models.IntegerField(unique=True)),
            ],
        ),

        # Alter UserInfo mobile_no field
        migrations.AlterField(
            model_name='userinfo',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),

        # Create Cart model
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='rannaghoreprotidinapp.products')),
            ],
        ),

        # Create Order model
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrate_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.IntegerField(unique=True)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'),
                             ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'),
                             ('refunded', 'Refunded')], default='pending', help_text='Current status of the order',
                    max_length=20)),
                ('admin_notes',
                 models.TextField(blank=True, help_text='Internal notes for this order (not visible to customer)',
                                  null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              to='rannaghoreprotidinapp.products')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-ctrate_date'],
            },
        ),
    ]